from utils.constants import *

__all__ = [
    'APP_VERSION', 'APP_NAME', 'DEFAULT_WINDOW_SIZE', 'MIN_WINDOW_SIZE',
    'DEFAULT_PAGE_SIZE', 'MAX_SHUFFLE_COUNT', 'MIN_SHUFFLE_COUNT', 'DEFAULT_SHUFFLE_COUNT',
    'MIN_RATING', 'MAX_RATING', 'UNCATEGORIZED', 'DEFAULT_CATEGORIES',
    'STOP_WORDS', 'MIN_KEYWORD_LENGTH', 'TFIDF_THRESHOLD',
    'MIN_DOCUMENT_FREQUENCY', 'MAX_DOCUMENT_FREQUENCY'
]